AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.6.0

Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/MethodLength:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockNesting:
  Max: 4
Metrics/BlockLength:
  Max: 120
Metrics/ClassLength:
  Max: 450
Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/ParameterLists:
  Max: 10
Layout/AlignParameters:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 30
Metrics/LineLength:
  Max: 120
Style/MultilineBlockChain:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  MinNameLength: 1
