docker:
  image: yegor256/rultor-image:1.9.1
architect:
- yegor256
- davvd
assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
install: |
  sudo apt-get -y update
  sudo apt-get -y install libcurl4-openssl-dev
  sudo bundle install --no-color "--gemfile=$(pwd)/Gemfile"
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1

    export RUBYOPT="-W0"
    sed -i "s/0\.0\.0/${tag}/g" lib/zold/version.rb
    bundle exec rake --quiet
    git add lib/zold/version.rb
    git commit -m "version set to ${tag}"
    gem build zold.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
merge:
  script: |-
    bundle exec rake --quiet
    pdd -f /dev/null -v
