language: ruby
rvm:
  - 2.3.3
  - 2.4.4
  - 2.5.1
  - ruby-2.6.0-preview1
cache: bundler
branches:
  only:
    - master
install:
  - travis_retry bundle update
  - gem install pdd
script:
  - pdd -f /dev/null
  - rake --quiet
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
