version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 24
    - RUBY_VERSION: 25
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - gem install openssl -- --with-openssl-dir=C:/OpenSSL-Win64
  - bundle install
build: off
before_test:
  - ruby -v
  - gem -v
  - bundle -v
test_script:
  - rake
cache:
  - vendor/bundle
