version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 24
    - RUBY_VERSION: 25
install:
  - cmd: set PATH=C:\Ruby%RUBY_VERSION%-X64\bin;%PATH%
  - ps: |
      $Env:openssl_dir = "C:/OpenSSL-Win64/bin"
  - cmd: ruby --version
  - cmd: git --version
  - cmd: bundle config --local path vendor/bundle --with-ssl-dir=%openssl_dir%
build_script:
  - bundle update
  - bundle install
test_script:
  - rake
cache:
  - vendor/bundle
