version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 24
    - RUBY_VERSION: 25
install:
  - ps: |
      $Env:PATH = "C:\Ruby${RUBY_VERSION}-X64\bin;${Env:PATH}"
      if ($Env:ruby_version -match "^23" ) {
        # RubyInstaller; download OpenSSL headers from OpenKnapsack Project
        $Env:openssl_dir = "C:/Ruby${RUBY_VERSION}-X64"
        appveyor DownloadFile http://dl.bintray.com/oneclick/OpenKnapsack/x64/openssl-1.0.2j-x64-windows.tar.lzma
        7z e openssl-1.0.2j-x64-windows.tar.lzma
        7z x -y -oC:\Ruby${RUBY_VERSION}-X64 openssl-1.0.2j-x64-windows.tar
      } else {
        # RubyInstaller2; openssl package seems to be installed already
        $Env:openssl_dir = "C:/msys64/mingw64"
      }
  - cmd: ruby --version
  - cmd: git --version
  - cmd: bundle config --local path vendor/bundle --with-ssl-dir=%openssl_dir%
build_script:
  - bundle update
  - bundle install
test_script:
  - rake
cache:
  - vendor/bundle
